/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package From_End;

import com.j256.ormlite.dao.Dao;
import com.j256.ormlite.dao.DaoManager;
import com.j256.ormlite.jdbc.JdbcConnectionSource;
import com.j256.ormlite.support.ConnectionSource;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static java.lang.String.format;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import org.h2.command.dml.Select;

/**
 *
 * @author Jeison
 */
public class formulario extends javax.swing.JFrame {
static Dao<Gestor,Integer> bd;
    
     public static void List1(JComboBox transaccion){
        //agregamos los items
        transaccion.addItem("Ingresos");
        transaccion.addItem("Gastos");
        
        
        //ojo : addItem -> sirve para agregar items a un combobox
    }
    
    //creamos un metodo que agregue items al combobox 2
    public  static void List2(JComboBox transaccion,JComboBox categ){
        categ.removeAllItems();
        switch (transaccion.getSelectedItem().toString()) {
            case "Ingresos":
                categ.addItem("Sueldo");
                categ.addItem("Otro ingreso");
               
                break;
            case "Gastos":
                categ.addItem("Alimentación");
                categ.addItem("Arriendo");
                categ.addItem("Servicios");
                categ.addItem("Educación");
                categ.addItem("Ocio");
		categ.addItem("Transporte");
                categ.addItem("Otros");
                    break;
           
            default:
        }
    
    
    
    }
      public formulario() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        formulario.List1(transaccion);
        
            
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        fecha = new com.toedter.calendar.JDateChooser();
        transaccion = new javax.swing.JComboBox<>();
        detalle = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        categ = new javax.swing.JComboBox<>();
        id = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        valor = new javax.swing.JFormattedTextField();
        idtxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor IMT");
        setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Consecutivo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 21, 100, 30));

        jLabel2.setText("Tipo transacción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 72, 100, 30));

        jLabel3.setText("Fecha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 122, 100, 30));

        jLabel4.setText("Valor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 222, 100, 30));

        jLabel5.setText("Categoria");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 172, 100, 30));

        jLabel6.setText("Detalle");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 272, 100, 30));

        borrar.setBackground(new java.awt.Color(255, 51, 51));
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        borrar.setToolTipText("Eliminar ");
        borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarMouseClicked(evt);
            }
        });
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 334, -1, -1));

        editar.setBackground(new java.awt.Color(255, 255, 255));
        editar.setForeground(new java.awt.Color(255, 255, 255));
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        editar.setToolTipText("Modificar");
        editar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarMouseClicked(evt);
            }
        });
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 334, -1, -1));
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 122, 180, 30));

        transaccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                transaccionItemStateChanged(evt);
            }
        });
        transaccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaccionMouseClicked(evt);
            }
        });
        transaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaccionActionPerformed(evt);
            }
        });
        getContentPane().add(transaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 72, 180, 30));

        detalle.setColumns(2);
        detalle.setToolTipText("");
        detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleActionPerformed(evt);
            }
        });
        getContentPane().add(detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 272, 180, 30));

        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        guardar.setToolTipText("Nuevo");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 334, -1, -1));

        categ.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                categItemStateChanged(evt);
            }
        });
        categ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categMouseClicked(evt);
            }
        });
        categ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categActionPerformed(evt);
            }
        });
        getContentPane().add(categ, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 172, 180, 30));

        id.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 63, 33));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C.#", "Tipo transacción", "Fecha", "Categoria", "Valor", "Detalle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaDatos.setEnabled(false);
        jScrollPane2.setViewportView(TablaDatos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 47, 652, 375));

        valor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 227, 180, 34));
        getContentPane().add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 14, 250, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarActionPerformed

    private void transaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaccionActionPerformed
      formulario.List2(transaccion, categ);
      // TODO add your handling code here:
    }//GEN-LAST:event_transaccionActionPerformed

    private void detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalleActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        double a = 0;
        try {
            int i = Integer.parseInt(id.getText());
            String t = transaccion.getSelectedItem().toString();
            Date f = fecha.getDate();
            String formatodate ="dd/MM/yyyy";
            SimpleDateFormat formateador = new SimpleDateFormat(formatodate);
            String r = formateador.format(f);
            String c = categ.getSelectedItem().toString();
            if(t.equalsIgnoreCase("Ingresos")) {
                a = Double.parseDouble(valor.getText());}
                else {
                a = Double.parseDouble(valor.getText())*-1;
                  
                        }
            double v = a;
             
            String d= detalle.getText();
            
            Gestor g = new Gestor(i,t,r,c,v,d);
            
            bd.create(g);
           
      
    } catch (SQLException ex) {
       JOptionPane.showMessageDialog(null, "Ocurrio un error y no pudimos guardar");

        
       
       
    }
        DefaultTableModel tb =(DefaultTableModel) TablaDatos.getModel();
        tb.setRowCount(0);
        NumberFormat formatter = NumberFormat.getCurrencyInstance();
        NumberFormat formater1= NumberFormat.getNumberInstance();
        
        
        try {
            for (Gestor gestor : bd.queryForAll()) {
             
              Object [] fila ={gestor.getId(),gestor.getTransaccion(),gestor.getCategoria(), gestor.getFecha(),gestor.getValor(),gestor.getDetalle()};
                tb.addRow(fila);
                
            }
            int contar =tb.getRowCount();
            double suma =0;
            for ( int i =0 ; i < contar ; i++ ){
                //suma = String.valueOf(  tb.getValueAt(i, 4).toString());
              suma =  suma+Double.parseDouble(tb.getValueAt(i, 4).toString());
            }
         
           Object [] fila2 ={null,null,null,"Total",String.valueOf(formatter.format(suma)),null};
                tb.addRow(fila2);
        } 
        catch (SQLException ex) {
            Logger.getLogger(formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        int txt = Integer.parseInt(String.valueOf(tb.getRowCount()-1));
           idtxt.setText(String.valueOf("Numero de movientos : "+txt)); 
    }//GEN-LAST:event_guardarActionPerformed

    private void transaccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_transaccionItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_transaccionItemStateChanged

    private void transaccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_transaccionMouseClicked

    private void categItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_categItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_categItemStateChanged

    private void categMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_categMouseClicked

    private void categActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categActionPerformed

    private void editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarMouseClicked
        // TODO add your handling code here:
        double a = 0;
        try {
            int i = Integer.parseInt(id.getText());
            String t = transaccion.getSelectedItem().toString();
            Date f = fecha.getDate();
            String formatodate ="dd/MM/yyyy";
            SimpleDateFormat formateador = new SimpleDateFormat(formatodate);
            String r = formateador.format(f);
            String c = categ.getSelectedItem().toString();
             if(t.equalsIgnoreCase("Ingresos")) {
                a = Double.parseDouble(valor.getText());}
                else {
                a = Double.parseDouble(valor.getText())*-1;
                  
                        }
            double v = a;
            String d= detalle.getText();
            
            Gestor g = new Gestor(i,t,r,c,v,d);
           
            bd.update(g);
            
            JOptionPane.showMessageDialog(null, "Perfecto! Informacion cambiada!");
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error!");
        }
        DefaultTableModel tb =(DefaultTableModel) TablaDatos.getModel();
        tb.setRowCount(0);
        NumberFormat formatter = NumberFormat.getCurrencyInstance();
        NumberFormat formater1= NumberFormat.getNumberInstance();
        
        
        try {
            for (Gestor gestor : bd.queryForAll()) {
             
              Object [] fila ={gestor.getId(),gestor.getTransaccion(),gestor.getCategoria(), gestor.getFecha(),gestor.getValor(),gestor.getDetalle()};
                tb.addRow(fila);
                
            }
            int contar =tb.getRowCount();
            double suma =0;
            for ( int i =0 ; i < contar ; i++ ){
                //suma = String.valueOf(  tb.getValueAt(i, 4).toString());
              suma =  suma+Double.parseDouble(tb.getValueAt(i, 4).toString());
            }
         
           Object [] fila2 ={null,null,null,"Total",String.valueOf(formatter.format(suma)),null};
                tb.addRow(fila2);
        } 
        catch (SQLException ex) {
            Logger.getLogger(formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         int txt = Integer.parseInt(String.valueOf(tb.getRowCount()-1));
           idtxt.setText(String.valueOf("Numero de movientos : "+txt));
    }//GEN-LAST:event_editarMouseClicked

    private void borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseClicked
        // TODO add your handling code here:
        int i = Integer.parseInt(id.getText());
        
        try {
            Gestor g = bd.queryForId(i);
            if (g != null) {
                bd.delete(g);
                DefaultTableModel tb =(DefaultTableModel) TablaDatos.getModel();
        tb.setRowCount(0);
        NumberFormat formatter = NumberFormat.getCurrencyInstance();
        NumberFormat formater1= NumberFormat.getNumberInstance();
        
        
        try {
            for (Gestor gestor : bd.queryForAll()) {
             
              Object [] fila ={gestor.getId(),gestor.getTransaccion(),gestor.getCategoria(), gestor.getFecha(),gestor.getValor(),gestor.getDetalle()};
                tb.addRow(fila);
                
            }
            int contar =tb.getRowCount();
            double suma =0;
            for ( int h =0 ; h < contar ; h++ ){
                //suma = String.valueOf(  tb.getValueAt(i, 4).toString());
              suma =  suma+Double.parseDouble(tb.getValueAt(h, 4).toString());
            }
         
           Object [] fila2 ={null,null,null,"Total",String.valueOf(formatter.format(suma)),null};
                tb.addRow(fila2);
        } 
        catch (SQLException ex) {
            Logger.getLogger(formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        int txt = Integer.parseInt(String.valueOf(tb.getRowCount()-1));
           idtxt.setText(String.valueOf("Numero de movientos : "+txt));  // TODO add your handling code here:
            }
            else {
                JOptionPane.showMessageDialog(null, "El codigo " + i + " no existe!");
                
            }
            
        } 
        catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null,  "No existe!");
        }
        
    }//GEN-LAST:event_borrarMouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        DefaultTableModel tb =(DefaultTableModel) TablaDatos.getModel();
        tb.setRowCount(0);
        NumberFormat formatter = NumberFormat.getCurrencyInstance();
        NumberFormat formater1= NumberFormat.getNumberInstance();
        
        
        try {
            for (Gestor gestor : bd.queryForAll()) {
             
              Object [] fila ={gestor.getId(),gestor.getTransaccion(),gestor.getCategoria(), gestor.getFecha(),gestor.getValor(),gestor.getDetalle()};
                tb.addRow(fila);
                
            }
            int contar =tb.getRowCount();
            double suma =0;
            for ( int i =0 ; i < contar ; i++ ){
                //suma = String.valueOf(  tb.getValueAt(i, 4).toString());
              suma =  suma+Double.parseDouble(tb.getValueAt(i, 4).toString());
            }
         
           Object [] fila2 ={null,null,null,"Total",String.valueOf(formatter.format(suma)),null};
                tb.addRow(fila2);
        } 
        catch (SQLException ex) {
            Logger.getLogger(formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         int txt = Integer.parseInt(String.valueOf(tb.getRowCount()-1));
           idtxt.setText(String.valueOf("Numero de movientos : "+txt));       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     * @throws java.sql.SQLException
     */
    public static void main(String args[]) throws SQLException {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  String nombrearchivo="jdbc:h2:./BD_Gestor";
  ConnectionSource url = new JdbcConnectionSource(nombrearchivo);
  bd = DaoManager.createDao(url,Gestor.class);
  
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                new formulario().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTable TablaDatos;
    javax.swing.JButton borrar;
    javax.swing.JComboBox<String> categ;
    javax.swing.JTextField detalle;
    javax.swing.JButton editar;
    com.toedter.calendar.JDateChooser fecha;
    javax.swing.JButton guardar;
    javax.swing.JFormattedTextField id;
    javax.swing.JLabel idtxt;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JComboBox<String> transaccion;
    javax.swing.JFormattedTextField valor;
    // End of variables declaration//GEN-END:variables

   
   
    }

